security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
      App\Entity\User:
        algorithm: bcrypt
    providers:
        my_provider:
          entity:
            class: App\Entity\User
            property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: my_provider
            guard:
              authenticators:
                - App\Security\LoginFormAuthenticator
            logout:
              path: app_logout
              target: /home
              invalidate_session: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
      - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/team, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/about, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/coach, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/comm, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/comp, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/contact, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/events, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/findUs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/gallery, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/playerReg, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/shop, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/orders, roles: IS_AUTHENTICATED_FULLY }
      # - { path: ^/, roles: ROLE_ADMIN }
